In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets

In [2]:
#Load data and return a dictionary of iris
iris = datasets.load_iris()
# Dữ liệu đầu vào - features matrix (150,4) - số bông hoa, các chỉ số đo (sepallen, sepalwid, petallen, petalwid)
iris_X = iris.data
# Dữ liệu đầu ra - label tương ứng mảng 1 chiều 150 con số tương ứng hàng của iris_X chỉ gồm 0,1,2 để phân loại hoa
iris_y = iris.target
print (f"Number of classes: {len(np.unique(iris_y))}")
print (f"Number of data point: {len(iris_y)}")

#Some samples of training data
X0 = iris_X[iris_y == 0, :]
print (f"\nSamples of class 0:\n {X0[:5,:]}")

X1 = iris_X[iris_y == 1, :]
print (f"\nSamples of class 1:\n {X1[:5,:]}")

X2 = iris_X[iris_y == 2, :]
print (f"\nSamples of class 2:\n {X2[:5,:]}")

Number of classes: 3
Number of data point: 150

Samples of class 0:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Samples of class 1:
 [[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]]

Samples of class 2:
 [[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]]


## Tách training data(100 point) và test data(50 point) use train_test_split trong sklearn.model_selection

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_X, iris_y, test_size=50)
print (f"Training size: {len(y_train)}")
print (f"Test size: {len(y_test)}")

Training size: 100
Test size: 50


In [4]:
model = neighbors.KNeighborsClassifier(n_neighbors = 1, p = 2)
#p = 2 la chuan khoang cach norm 2
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print ("Print results for 20 test data points")
print (f"Predict label: {y_pred[20:40]}")
print (f"Ground truth: {y_test[20:40]}")

Print results for 20 test data points
Predict label: [1 2 1 1 1 1 1 2 2 2 0 2 1 1 1 1 0 2 2 1]
Ground truth: [1 2 1 1 1 1 1 2 2 2 0 2 1 1 1 1 0 2 2 1]


## Phương pháp đánh giá (evaluation method)

In [5]:
from sklearn.metrics import accuracy_score
print (f"Accuracy of 1NN: {100*accuracy_score(y_test, y_pred):.2f}%")

Accuracy of 1NN: 96.00%


In [6]:
model = neighbors.KNeighborsClassifier(n_neighbors=10, p = 2)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print (f"Accuracy of 10NN: {100*accuracy_score(y_test, y_pred):.2f}%")

Accuracy of 10NN: 96.00%


In [10]:
model = neighbors.KNeighborsClassifier(n_neighbors=10, p = 2, weights= 'distance')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print (f"Accuracy of 10NN (1/distance weights): {100*accuracy_score(y_test, y_pred):.2f}%")

Accuracy of 10NN (1/distance weights): 96.84%


In [8]:
def myweight(distances):
    sigma2 = .5 # we can change this number
    return np.exp(-distances**2/sigma2)

clf = neighbors.KNeighborsClassifier(n_neighbors = 10, p = 2, weights = myweight)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print ("Accuracy of 10NN (customized weights): %.2f %%" %(100*accuracy_score(y_test, y_pred)))

Accuracy of 10NN (customized weights): 94.00 %


## KNN cho regression

In [9]:
import numpy as np
from mnist import MNIST
import matplotlib.pyplot as plt
from sklearn import neighbors
from sklearn.metrics import accuracy_score
import time

mndata = MNIST('D:/ML/MNIST') # path to your MNIST folder
mndata.load_training()
mndata.load_testing()
X_test = mndata.test_images
X_train = mndata.train_images
y_test = np.asarray(mndata.test_labels)
y_train = np.asarray(mndata.train_labels)
start_time = time.time()
model = neighbors.KNeighborsClassifier(n_neighbors=1, p = 2)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
end_time = time.time()
print (f"Accuracy of 1NN for MNIST: {100*accuracy_score(y_test, y_pred):.2f}%")
print (f"Running time: {(end_time-start_time):.2f}s")


Accuracy of 1NN for MNIST: 96.91%
Running time: 21.11s
